pkgs/proj/default.nix

- pkgs(proj): sync with nixpkgs upstream
- pkgs(proj): 9.1.0 -> 9.1.1

pkgs(proj): 9.1.0 -> 9.1.1

---

pkgs/geos/default.nix
pkgs/geos/tests.nix

- pkgs(geos): 3.11.0 -> 3.11.1
- pkgs(geos): add simple passthru test

pkgs(geos): add simple package test

---

pkgs/qgis/unwrapped.nix

nixpkgs upstream change:
https://github.com/NixOS/nixpkgs/commit/1666dc68b7edc3d5a9e65feac54a95dacdbcea92

pkgs(qgis): drop xlibsWrapper

---

.github/workflows/update-version.yml
flake.nix
pkgs/fiona/default.nix

- pkgs: add shapely package
- pkgs: add fiona package

pkgs: add fiona package

---

.github/workflows/update-version.yml
flake.nix
pkgs/rasterio/default.nix

- pkgs: add shapely package
- pkgs: add fiona package
- pkgs: add rasterio package

pkgs: add rasterio package

---

.github/workflows/update-version.yml
flake.nix
pkgs/geopandas/default.nix

- pkgs: add shapely package
- pkgs: add fiona package
- pkgs: add rasterio package
- pkgs: add geopandas package

pkgs: add geopandas package

---

.github/workflows/test-custom-packages.yml

- ci: test python3-fiona package with patched GDAL

ci: test if dev shell depends on patched GDAL package

---

pkgs/qgis/unwrapped-ltr.nix
pkgs/qgis/unwrapped.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/208692

pkgs(qgis): fix GRASS prefix

---

flake.nix
pkgs/qgis/unwrapped-ltr.nix
pkgs/qgis/unwrapped.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/208692

pkgs(qgis): disable qtwebkit by default

---

pkgs/fiona/default.nix

nixpkg change:
https://github.com/NixOS/nixpkgs/pull/215778/commits/43b92846277a81a43fa8d38f648938ceea75a09d

pkgs(fiona): sync with upstream changes

---

.github/workflows/build-packages.yml
.github/workflows/flake-update.yml
.github/workflows/test-custom-images.yml
.github/workflows/test-custom-packages.yml
.github/workflows/test-images.yml
.github/workflows/test-python-versions.yml
.github/workflows/test-shells.yml
.github/workflows/test-templates.yml
.github/workflows/update-packages.yml

Version 20 is fixing
https://github.com/cachix/install-nix-action/issues/161

ci: upgrade install-nix-action to v20

---

lib/postgresql-client-shell.nix
templates/simple/shells.nix
templates/workspace/flake.nix
tests/shells/flake.nix

* rename version parameter to postgresqlVersion
* rename port parameter to postgresqlPort
* add extraPackages parameter
* install PostGIS CLI tool (shp2pgsql, ...)

lib: refactor mkPostgresqlClientShell function

---

pkgs/geos/default.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/215844

pkgs(geos): add meta.pkgConfigModules

---

pkgs/rasterio/default.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/206742

pkgs(rasterio): switch to nativeCheckInputs

---

pkgs/rasterio/default.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/213152

pkgs(rasterio): add changelog to meta

---

pkgs/rasterio/default.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/213152

pkgs(rasterio): sync with nixpkgs

---

pkgs/gdal/default.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/206742

pkgs(gdal): switch to nativeCheckInputs

---

pkgs/gdal/default.nix

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/214045

pkgs(gdal): allow overriding libmysqlclient with mysql80

---

pkgs/proj/default.nix
pkgs/proj/only-add-curl-for-static-builds.patch
pkgs/pyproj/default.nix

Also contains Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/218719

pkgs(proj): 9.1.1 -> 9.2.0

---

.github/workflows/build-packages.yml
pkgs/owslib/default.nix

This change is also pulling all changes from Nixpkgs master.

pkgs(python3-owslib): 0.27.2 -> 0.28.1

---

pkgs/gdal/default.nix

- pkgs(gdal): 3.6.3 -> 3.6.4
- pkgs(gdal): fix build and tests on darwin

pkgs(gdal): 3.6.3 -> 3.6.4

---

pkgs/fiona/default.nix

Nixpkgs PR:
https://github.com/NixOS/nixpkgs/pull/234234

pkgs(python3-fiona): sync with nixpkgs

---

pkgs/grass/default.nix
pkgs/grass/tests.nix

Nixpkgs PR:
https://github.com/NixOS/nixpkgs/pull/241164

pkgs(grass): alphabetical reordering of dependencies and adding package tests

---

.github/workflows/build-packages.yml
.github/workflows/test-geonixcli.yml
pkgs/geonixcli/geonix.bash
pkgs/geonixcli/templates/init/dot-envrc
pkgs/geonixcli/templates/init/geonix.nix

- pkgs(geonixcli): add direnv file to geonix init
- pkgs(geonixcli): temporary disable geonix override
- pkgs(geonixcli): add geonix help command
- pkgs(geonixcli): update geonix.nix init template file

pkgs(geonixcli): multiple improvements

---

pkgs/gdal/default.nix
pkgs/gdal/tests.nix
pkgs/geos/tests.nix

- pkgs(gdal): 3.8.1 -> 3.8.2
- pkgs(gdal): call correct binaries in tests
- pkgs(geos): fix package test script name

pkgs: nixpkgs weekly pull 20231222

---

pkgs/qgis/unwrapped-ltr.nix
pkgs/qgis/unwrapped.nix

- pkgs(qgis): 3.34.1 -> 3.34.2
- pkgs(qgis-ltr): 3.28.13 -> 3.28.14

pkgs: nixpkgs weekly pull 20240105

---

flake.nix
pkgs/geopandas/default.nix
pkgs/grass/nixpkgs/wxpython-rename.patch
pkgs/pdal/default.nix
pkgs/pdal/tests.nix

- pkgs(grass): add nixpkgs-pull reverse patch
- pkgs(python3-geopandas): 0.14.1 -> 0.14.2
- pkgs(pdal): add unit and package tests
- flake: enable pdal package tests

pkgs: nixpkgs weekly pull 20240112

---

pkgs/qgis/unwrapped-ltr.nix
pkgs/qgis/unwrapped.nix
pkgs/tiledb/default.nix

- pkgs(qgis-ltr): 3.28.14 -> 3.28.15
- pkgs(qgis): 3.34.2 -> 3.34.3
- pkgs(tiledb): fixup build

pkgs: nixpkgs weekly pull 20240126

---

flake.nix
pkgs/gdal/default.nix
pkgs/gdal/nixpkgs/gdal-tests.patch
pkgs/gdal/tests.nix
pkgs/geonixcli/templates/override/overrides.nix
pkgs/geopandas/default.nix
pkgs/qgis/nixpkgs/qgis.patch
tests/shells/gdal.patch

- pkgs(gdal): add java bindings
- pkgs(python3-geopandas): 0.14.2 -> 0.14.3
- pkgs(qgis): update nixpkgs pull reverse patch

pkgs: nixpkgs weekly pull 20240208

---

DEVELOPMENT.md
flake.lock
pkgs/fiona/nixpkgs/cython.patch
pkgs/qgis/unwrapped-ltr.nix
pkgs/qgis/unwrapped.nix
pkgs/rasterio/nixpkgs/cython.patch
pkgs/shapely/nixpkgs/cython.patch

pkgs: weekly update (weekly-update-2024.17)

---

flake.lock
pkgs/geopandas/default.nix

pkgs: weekly update (weekly-update-2024.18)

---

flake.lock
pkgs/grass/nixpkgs/wrapgappshook.patch
pkgs/qgis/nixpkgs/wrapgappshook.patch

pkgs: weekly update (weekly-update-2024.19)

---

flake.lock
pkgs/owslib/default.nix

pkgs: weekly update (weekly-update-2024.20)

---

flake.lock
pkgs/gdal/master-rev.nix
pkgs/libgeotiff/default.nix
pkgs/qgis/qgis-ltr-plugins-list.nix
pkgs/qgis/qgis-plugins-list.nix

pkgs: weekly update (weekly-update-2024.22)

---

flake.lock
pkgs/fiona/default.nix
pkgs/fiona/nixpkgs/cython.patch
pkgs/gdal/master-rev.nix
pkgs/geopandas/default.nix
pkgs/owslib/default.nix
pkgs/postgis/nixpkgs/maintainers.patch
pkgs/postgis/postgis.nix
pkgs/proj/default.nix
pkgs/pyproj/default.nix
pkgs/qgis/qgis-ltr-plugins-list.nix
pkgs/qgis/qgis-plugins-list.nix
pkgs/rasterio/default.nix
pkgs/rasterio/nixpkgs/cython.patch
pkgs/rasterio/nixpkgs/replace.patch
pkgs/shapely/default.nix
pkgs/shapely/nixpkgs/cython.patch

pkgs: weekly update (weekly-update-2024.23)

---

flake.lock
flake.nix
pkgs/gdal/master-rev.nix
pkgs/geos/default.nix
pkgs/pdal/nixpkgs/laszip-name.patch
pkgs/qgis/3_38.nix
pkgs/qgis/qgis-ltr-plugins-list.nix
pkgs/qgis/qgis-plugins-list.nix
pkgs/qgis/set-pyqt-package-dirs-3_38.patch
pkgs/qgis/unwrapped-3_38.nix

pkgs: weekly update (weekly-update-2024.26)

---

flake.lock
pkgs/gdal/master-rev.nix
pkgs/grass/nixpkgs/grass-config-dir.patch
pkgs/grass/plugins-rev.nix
pkgs/qgis/nixpkgs/qgis-ltr-python.patch
pkgs/qgis/nixpkgs/qgis-python.patch
pkgs/qgis/nixpkgs/with-grass-false.patch
pkgs/qgis/qgis-ltr-plugins-list.nix
pkgs/qgis/qgis-plugins-list.nix

pkgs: weekly update (weekly-update-2024.32)
